import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const Pacifico = localFont({
  src: './fonts/PacificoRegular-BXvV.ttf',
  variable: '--font-pacifico',
  weight:'100 900',
})

export const metadata = {
  title: "iamscientist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Pacifico.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
